{
    "Life Style":None,
	"Family History":None,
	"Social History":None,
	"Medical\/Surgical History":"19-year history of uc, had undergone colonoscopy every year at a previous outpatient clinic; the patient had extensive colitis and had been treated with aminosalicylate for low disease activity without corticosteroid administration; after several years of asymptomatic uc, a 10-mm tumor was observed in the upper rectum; under a diagnosis of dysplasia-associated lesion or mass, the patient underwent endoscopic mucosal resection (emr) at the previous outpatient clinic","Signs and Symptoms":"histopathological findings after emr revealed focal adenocarcinoma with tubulovillous adenoma, with tumor cells remaining in the resected margin; re-examination with colonoscopy after emr revealed residual tumor at the resected site ; however, the macroscopic margin of the tumor was unclear; a biopsy from the site of the erosive margin of the tumor revealed high-grade dysplasia; considering that this patient with uc and carc was elderly, laparoscopic total proctocolectomy combined with abdominoperineal resection and ileostomy was performed to avoid the risk of residual cancer and fecal incontinence; the resulting resected specimen showed well-differentiated tubular adenocarcinoma with a component of mucinous adenocarcinoma, and dysplastic epithelium was observed in the area surrounding the cancer lesion; furthermore, abnormal p53 accumulation was found by immunohistochemical examination, which was compatible with carc; the cancer invaded the muscular layer without node metastasis, and therefore was eventually diagnosed as pt2 and pn0, stage i according to the union for international cancer control (uicc)",
	"Comorbidities":None,
	"Diagnostic Techniques and Procedures":"abdominal enhanced ct revealed partial intrahepatic bile duct dilation in the left lateral section of the liver, and endoscopic retrograde cholangiography demonstrated stenosis and dilation of the bile duct in the left lateral sector; at the same time, cholangiography demonstrated a pruned-tree appearance in the bile duct of the right lobe which led to a suspicious diagnosis of primary sclerotic cholangitis; however, brush cytology of the stenotic site revealed no malignancy; , although a malignant tumor of the bile duct could still not be observed, the possibility of icc at the stenosis in the hepatic duct was suspected because biliary stenosis with atrophy of the left lateral section had not changed; , after the left hepatectomy, an intraoperative diagnosis of adenocarcinoma in the liver was made, and abnormal cells were observed in the left bile duct at the first resected site; an additional resected specimen of the left bile duct and caudate branch revealed no malignant tumor; the resected specimen showed a bile duct carcinoma of 2 cm in diameter and stenosis of the hepatic duct wall, which represented an icc of the periductal infiltration invading the left branch of the portal vein; the primary well-differentiated tubular adenocarcinoma infiltrating the liver parenchyma was diagnosed histologically; in addition, an onion-skin appearance indicating psc was found in the non-cancerous region of the liver ; finally, the periductal infiltration type was classified as t4, and was diagnosed as pt4 and pn0, stage iva according to the uicc classification; the patient was discharged after an uneventful postoperative period; a month after the hepatectomy the patient\u2019s ca19-9 level returned to normal (14.1 u\/ml); adjuvant therapy for icc consisting of combination therapy of gemcitabine and s-1 was administered for 6 months",
	"Diagnosis":None,"Laboratory Values":"at the same time of admission for surgery for carc, the patient\u2019s laboratory data revealed elevated c-glutamyltransferase and alkaline phosphatase levels of 133 and 371 iu\/l, respectively. the aspartate transaminase and alanine transaminase levels were normal, and the carbohydrate antigen 19-9 (ca19-9) level was 32.3 u\/ml. , at 6 months after the total proctocolectomy, the patient\u2019s laboratory data revealed elevation of his ca19-9 level to 56.4 u\/ml",
	"Pathology":None,
	"Pharmacological Therapy":None,
	"Interventional Therapy":"therefore, we decided to perform a left hepatectomy and to attempt intraoperative pathological diagnosis in the cut edge of the bile duct to determine whether to add extrahepatic bile duct resection",
	"Patient Outcome Assessment":"the patient remains alive and has been followed-up for 2.5 years after hepatectomy with no recurrence of icc or colitic cancer observed",
	"Age":73.0,
	"Gender":"male",
	"PDF Path":"MACCR\/Tsuchiya et al. - 2017 - A case of concomitant colitic cancer and intrahepa.pdf"
}

{
	"Life Style": None,
	"Family History": "father had died at 76 years of age after having suffered a stroke and that he had hypertension, diabetes and a history of depression including a suicide attempt; mother is 76 years old and in good health; three younger brothers, the oldest of whom is 51 years old and has been diagnosed with cerebellar atrophy; he also has dysarthira and cerebellar ataxia; those symptoms had gradually developed within the previous 2 years; second brother had suffered from depression and had committed suicide 20 years previously; youngest brother had no health issues, but his 17-year-old son had been diagnosed with epilepsy; a son and a daughter; her son suffers from migraine attacks but her daughter is healthy",
	"Social History": "premorbid personality was described as reserved, diligent, frugal, and calm; had worked in a market for more than 20 years; begun to argue over seemingly unimportant matters with her neighbors; begun to impulse buy multiple items also make many unnecessary purchases for her family; very hyperactive in her work life and social life; husband had an explosive temperament and alcohol problems which were a source of great stress and concern for her",
	"Medical\/Surgical History": "changes in her personality had begun to appear in 2008 and her symptoms of hostility had become more severe recently; she and her family denied that had experienced any depressive episodes or had ever been diagnosed with a mood disorder; no history of head trauma but had hypertension and diabetes; no history of migraine, a prior tia, or stroke",
	"Signs and Symptoms": "excessively talkative, impulsive, and verbally aggressive; during the previous 5 years, she had begun to speak garrulously and often lost the thread of a conversation and included many irrelevant details when providing an explanation; she had become much more easily irritable and angry, which took the form of yelling and throwing objects; did not display any sleep or eating disorders at the time of her visit; no evidence of delusions or hallucinations; pressured speech, circumstantiality, labile moods, poor impulse control, and made grandiose plans; no insights into the changes in her personality and behavior; neuropsychological testing revealed total scores that were within the normal range (k-mmse 29\/30); montreal cognitive assessment test (moca-k 25\/30) revealed a failure to perform the trail making test (tmt) and copy cube; normal ability to encode and retrieve verbal information; attention and inhibitory control function were found to be severely impaired; cognitive productivity was also poor; potential for perseveration was therefore low, and she showed an impaired efficient sorting tendency; strong cognitive rigidity; complaining of physical pain or discomfort and making efforts to cope with difficulties in her cognitive function; results of routine laboratory tests including vdrl, hiv antibodies and thyroid function were also unremarkable apart from hyperlipidemia; severe leukoencephalopathy; high signal intensity found by t2 weighted images (t2w1) and low signal intensity in the left pons; high signal intensity was prominent on the periventricular white matter, both basal ganglia, thalamus, and the external capsule; a heterogeneous mutation was detected in this patient that causes an arginine to proline substitution in exon 3 of chromosome 19 p13.2-13.1 (c.224g > c); manic symptoms, including a labile mood, talkativeness and impulsivity; at the time of discharge, she was no longer hostile or aggressive but still showed slight impulsivity and mood instability symptoms",
	"Comorbidities": "hypertension; diabetes",
	"Diagnostic Techniques and Procedures": "neuropsychological testing; montreal cognitive assessment test; trail making test (tmt); copy cube; luria\u2019s fist-edge-palm test; loop test; bgt; clock drawing test; color trail test (ctt) 1\/2; korean auditory verbal learning test (k-avlt); stroop test; word\/figural fluency test; executive complex figure test; grooved pegboard test; finger tapping test; hand dynamometer; mmpi-ii; sentence completion test (sct); wisconsin card sorting test (wcst); rorschach test; laboratory tests; mri analysis of the brain; t2 weighted images (t2w1); fluid-attenuated inversion-recovery (flair); genetic testing for notch3 mutations",
	"Diagnosis": "cadasil; suspected late-onset bipolar disorder with chronic manic features",
	"Laboratory Values": None,
	"Pathology": None,
	"Pharmacological Therapy": "medications for a depressed mood and insomnia; both antidepressants and sleeping pills; atypical antipsychotics (quetiapine, 800 mg) and benzodiazepine (bromazepam, 6 mg); amlodipine (novasc), metformin (diabex), and atorvastatin (lipitor)",
	"Interventional Therapy": None,
	"Patient Outcome Assessment": "able to be discharged after two weeks in hospital",
	"Age": 53.0,
	"Gender": "female",
	"PDF Path": "MACCR\/Park et al. - 2014 - Case report bipolar disorder as the first manifes.pdf"
}

{
	"Life Style": None,
	"Family History": None,
	"Social History": None,
	"Medical\/Surgical History": None,
	"Signs and Symptoms": "epigastralgia one day prior to admission",
	"Comorbidities": None,
	"Diagnostic Techniques and Procedures": "laboratory data taken on admission: elevation of aminotransferase, alanine aminotransferase, ?-guanosine triphosphate, and alkaline phosphatase; abdominal computed tomography (ct) and magnetic resonance cholangiopancreatography (mrcp) showed a mass in an enlarged gallbladder and bulky hepatic lymph nodes surrounding the hepatic hilum; there were also no apparent lesions in upper and lower gastrointestinal endoscopy; endoscopic ultrasound-guided fine-needle aspiration (eus-fna) was performed to obtain tissue from the hilar lymph node; ihc staining of the specimen was done as well; bile cytology was also done; positron emission tomography\/computed tomography (pet\/ct) examination was performed to evaluate other primary or metastatic lesions; it revealed that no other accumulated lesions were identified, and the accumulation of 18f fluorodeoxyglucose (fdg) was in the gallbladder (suvmax 7.8) and lymph nodes (suvmax 13.4); as the result of thorough pathological re-evaluation by total segmentation, a negligible area of adenocarcinoma was detected in the lymph nodes; during the first course of chemotherapy, neutropenia occurred; grade 4 neutropenia and anemia developed during the second line course, and she needed to receive pegylated granulocyte colony-stimulating factor and red blood cell transfusion",
	"Diagnosis": "gallbladder nec that was confined to the regional hepatic hilar lymph nodes metastasis; after 4 months, multiple recurrences in the para-aortic lymph nodes were detected, which was pathologically demonstrated via eus-fna to be nec; neuroendocrine carcinoma in the hepatic hilar lymph nodes concomitant with an adenocarcinoma of the gallbladder",
	"Laboratory Values": "laboratory data on admission revealed an elevation of aminotransferase, alanine aminotransferase, ?-guanosine triphosphate, and alkaline phosphatase. serum total bilirubin and tumor markers, carcinoembryonic antigen (cea), carbohydrate antigen 19-9 (ca19-9), span-1, and neuron-specific enolase (nse), were all within normal ranges. during the first course of chemotherapy, neutropenia occurred",
	"Pathology": "immunohistochemical staining of the specimen identified diffuse positivity for keratin, cd56, and synaptophysin in the tumor cells, which is consistent with nec. the bile cytology revealed class v malignant cells. macroscopically, the tumor was 58 \u00d7 42 mm in size and was located in the fundus, which contained a yellowish gallstone (fig. 2a). a portion of the hepatic hilar lymph nodes (71 \u00d7 37 mm) was also excised separately (fig. 2b). microscopic examination of the gallbladder revealed a moderate to well differentiated tubular adenocarcinoma infiltrating from the mucosa to the muscular layer, but not the serosal surface, without any nec components (fig. 2c, d). the tumor cells in the gallbladder are slightly positive for synaptophysin and cd56, but negative for chromogranin a (fig. 2e\u2013g). the resection margin from the liver bed was negative for tumor cells. the epithelium around the carcinoma showed intestinal metaplasia with the goblet cells (fig. 4a), which area was stained by alcian blue (fig. 4b). on the other hand, the hepatic hilar lymph nodes were composed of small round tumor cells with hyperchromatic nuclei and scant cytoplasm (fig. 3a). some of the tumor cells were large and had vesicular nuclei. the tumor cells were arranged in sheets, cords, or in a trabecular or rosette fashion and were interspersed with focal necrosis. they were immunohistochemically positive for cd56, synaptophysin, and chromogranin a (fig. 3b\u20133d). the mitotic count was 24 per 10 high-power microscopic fields, and the ki-67 proliferation index was 70\u201380%, consistent with nec. the surgical dissection margin of the hepatic lymph nodes was microscopically cauterized within the tumor cells. there was no invasion to the extrahepatic biliary duct. a negligible area of adenocarcinoma was detected in the lymph nodes (fig. 3e, f). the adenocarcinoma component and the intestinal metaplastic epithelium in the gallbladder were both positive for cdx2 (fig. 4a), but the neuroendocrine component in hilar lymph nodes was negative for cdx2 (fig. 4b). after 4 months, multiple recurrences in the para-aortic lymph nodes were detected, which was pathologically demonstrated via eus-fna to be nec",
	"Pharmacological Therapy": "postoperatively, the patient received three cycles of carboplatin (area under the curve of 5 on day 1 repeated every 21 days) and etoposide (80 mg\/m2 on days 1 through 3 repeated every 21 days). during the first course, grade 4 neutropenia occurred and it was managed with prophylactic fluoroquinolones. the patient underwent second-line chemotherapy, after recurrences in the para-aortic lymph nodes were detected, with amrubicin (24 mg\/m2 on days 1 through 3 repeated every 21 days)",
	"Interventional Therapy": "an endoscopic naso-gallbladder drainage (engbd) catheter was placed; we decided to perform surgical resection prior to chemotherapy because of concerns about complications developing from mechanical obstruction of the hepatic hilum by the enlarged lymph node; she underwent cholecystectomy, hepatic hilar lymphadenectomy, extrahepatic biliary duct resection, and hepaticojejunostomy; the bulky lymph nodes were totally resected as \u201cen bloc\u201d; there were no apparent residual lesions surgically",
	"Patient Outcome Assessment": "the postoperative course was uneventful and she was discharged on the tenth day after surgery; her cancer returned in the para-aortic lymph nodes, and she died of progressive disease 8 months after surgery",
	"Age": 76.0,
	"Gender": "female",
	"PDF Path": "MACCR\/Okada et al. - 2016 - A case of neuroendocrine carcinoma in the hepatic .pdf"
}